import Head from 'next/head';
import Image from 'next/image';
import Dapp from '../components/Dapp';
import styles from '../styles/Home.module.css';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dapp />
    </div>
  );
};

export default Home;
